#!/usr/bin/env python3
import modules.PySimpleGUI as sg

from modules.dbInterface import loadImagelistFromDB, loadImageFromDB, saveImageToDB, deleteImageFromDB



    
#Load database
imagelist=loadImagelistFromDB()

layout = [
    [sg.Image(size = (500,300), key = 'image')], [sg.Listbox(imagelist,size = (100,25),enable_events=True,key ='image_list')],
    [sg.Button("Delete", key = "delete_image")],[sg.Button("Add", key = "add_image")],
    ]
    
window = sg.Window('Viewer', layout)

while True:
     event, values = window.read()
    
     if event == "Quit" or event == sg.WIN_CLOSED:
         break
        
     if event == 'image_list':
        print("Image selected: ")
        print(values['image_list'])        
        imageData = loadImageFromDB( values['image_list'])
       
        #print(imageData[0])
       
        window['image'].update(data=imageData[0],subsample=3)
        #TODO updte canvas with imageData
        
     if event == 'add_image':
        imageFilename = sg.popup_get_file(" ",no_window=True, file_types=(('Images', '.png'),('Images', '.jpg')))   
        if not imageFilename:
           continue
        saveImageToDB(imageFilename)
        imagelist=loadImagelistFromDB()
        window["image_list"].update(imagelist) 
        
     if event == "delete_image":
        if sg.popup_yes_no("Are you sure you want to delete this image?") == "Yes":
            try:
              index = int(''.join(map(str, window["image_list"].get_indexes())))
              rowToDelete = imagelist.pop(index)
              deleteImageFromDB(rowToDelete)
            except ValueError:
              sg.Popup("Select an image to delete!")  

            window["image_list"].update(imagelist) 
            window["image"].update()                         
        
        
